// Next.js
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import localFont from "next/font/local";

// Next-Intl
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";

// CSS
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationBar from "@/components/layout/NavigationBar";

const generalSans = localFont({
  variable: "--font-general-sans",
  display: "swap",
  src: [
    {
      path: "../../assets/fonts/general_sans/GeneralSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/fonts/general_sans/GeneralSans-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/general_sans/GeneralSans-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/general_sans/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

const neueRegrade = localFont({
  variable: "--font-neue-regrade",
  display: "swap",
  src: [
    {
      path: "../../assets/fonts/neue_regrade/NeueRegradeBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/fonts/neue_regrade/NeueRegradeSemibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/neue_regrade/NeueRegradeMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/neue_regrade/NeueRegradeRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${generalSans.variable} ${neueRegrade.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
          forcedTheme="light"
        >
          <NextIntlClientProvider>
            <NavigationBar />
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
